name: IOS build
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: macos-latest
    env:
      CXXFLAGS: -std=${{ matrix.standard }}
      TEST_BUILD_MODULES: 
    steps:
      - uses: actions/checkout@v2
      - name: Running IOS build workflow.
        run: ./make/build ${{ matrix.compiler }}
    strategy:
      matrix:
        compiler:
          - g++-10
        standard:
          - c++14

